### ISSUE TITLE
Cant be built on Windows

### ISSUE THREAD

**Issue by SlamWeasel** [ascpixi/smolsharp#4]
Tho the sln is set up as a C# project, the SmolSharp.props contains two <Exec Command="objcopy/> in lines 60 and 61, objcopy being a command that does not normally exist in Windows and I was not able to find an equivalent with all the needed features

**Comment by ascpixi** [comment]
Thanks for the interest in the project! Yes, SmolSharp calls `objcopy` to minimize the section alignment that is enforced by the MSVC linker and to remove all exception handling information. Unfortunately, I couldn't find a way to force the linker to do this on its own, and there don't seem to be any tools available that are built for Windows. The closest tool I could find was `lib.exe`, packaged with MSVC, which can only remove individual symbols - not entire sections.

On my installation, the `objcopy` binary is provided by [MinGW](https://www.mingw-w64.org/downloads/). Try installing it and make sure the binaries are on your `PATH` environment variable.

**Comment by ascpixi** [comment]
As a work-around, you may also simply remove these two lines here:

https://github.com/ascpixi/smolsharp/blob/5764b6b1e5efa12f06f6acba9bc5e7955ac8326e/src/SmolSharp.props#L60-L61

However, you will see a size increase - a 678 byte regression for the Ocean demo, for example (!)

**Comment by SlamWeasel** [comment]
Thank you for the info

I think that its a very insightful experiment, and in a way its hilarious that the solution to "How do I reduce bloated file sizes in C#" is in this case "Write C++ Code"
